In [6]:
import numpy as np

In [17]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X,axis=0)
y = y/100
print("X=",X)
print("Y=",y)

X= [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Y= [[0.92]
 [0.86]
 [0.89]]


In [31]:
X

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [33]:
y

array([[0.92],
       [0.86],
       [0.89]])

In [18]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [19]:
def derivatives_sigmoid(x):
    return x * (1 - x)

In [20]:
epoch=500 
lr=0.1 
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1 

In [21]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [22]:
for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+ bout
    output = sigmoid(outinp)

In [23]:
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)

In [24]:
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

In [27]:
    wout += hlayer_act.T.dot(d_output) *lr
    wh += X.T.dot(d_hiddenlayer) *lr

In [28]:
print("\n Input: \n" + str(X))
print("\n Actual Output: \n" + str(y))
print("\n Predicted Output: \n" ,output)


 Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

 Actual Output: 
[[0.92]
 [0.86]
 [0.89]]

 Predicted Output: 
 [[0.74986751]
 [0.73134547]
 [0.74555676]]
